# Use an official Golang runtime as a parent image
FROM golang:1.16-alpine

# # Install Beego and its dependencies
RUN apk add --no-cache git && \
    go get github.com/astaxie/beego@v1.12.3 && \
    go get github.com/beego/bee@v1.12.3 && \
    go get github.com/go-delve/delve/cmd/dlv

WORKDIR /go/src/haste

COPY ./src/haste .

# RUN go build -o main .

RUN go mod download
RUN go mod tidy

EXPOSE 2345

CMD ["dlv", "--listen=:2345", "--headless=true", "--api-version=2", "exec", "haste", "--check-go-version=false"]
