version: '3.7'

services:
  haste:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    env_file: ${ENV_FILE}
    ports:
      - ${HASTE_HOST_PORT}:8080
    volumes:
      - ./src/haste:/go/src/haste
    networks:
      - network-backend
  
  haste.debug:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile-debug
      context: .
    env_file: ${ENV_FILE}
    ports:
      - ${HASTE_HOST_PORT}:8080
      - 2345:2345
    volumes:
      - ./src/haste:/go/src/haste
    networks:
      - network-backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - network-backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  db-data:

networks:
  network-backend:
