version: '3.7'

services:
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    env_file: ${ENV_FILE}
    environment:
      - DB_HOST=db
    ports:
      - 8082:8080
      - 2345:2345
    volumes:
      - ./src/haste:/go/src/haste
    networks:
      - network-backend
  
  api.debug:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile-debug
      context: .
    env_file: ${ENV_FILE}
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./src/haste:/go/src/haste
    networks:
      - network-backend

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network-backend

volumes:
  db-data:

networks:
  network-backend:
